#!/bin/bash

#------------------------------------------
# Purpose: 
# Created Date:  Monday 30 May 2022 05:54:04 PM IST
# Author: Harsh Panchal

# Usage: 
#------------------------------------------

#script via TheeMahn

sudo umount /media/ISO

for I in `echo $*`
do
    foo=`gksudo -u root -k -m "enter your password for root terminal
    access" /bin/echo "got r00t?"`
    sudo mkdir /media/ISO
    sudo mount -o loop -t iso9660 $I /media/ISO
done
